###Crear
POST http://localhost:9000/api/marca HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "nombre": "SamSung",
    "estado": "Activo"
}


###Leer todos los datos
GET http://localhost:9000/api/marca HTTP/1.1
Authorization: Bearer 

###Leer datos por ID
GET http://localhost:9000/api/marca/6402b77e893a84525c1ca9fd HTTP/1.1
Authorization: Bearer 

###Actualizar
PUT http://localhost:9000/api/marca/6402b714893a84525c1ca9fa HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
   "nombre": "Xiaomi Redmi",
    "estado": "Activo"
}

###Eliminar
DELETE  http://localhost:9000/api/marca/6402b77e893a84525c1ca9fd HTTP/1.1
Authorization: Bearer 

