###Crear
POST http://localhost:9000/api/inventario HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "serial":"1010",
    "modelo":"Redmi  12  ",
    "descripción":"Redmi Note 12Pro 5G",
    "color":"Negro",
    "foto":"https://www.korolos.com.co/wp-content/uploads/2023/02/NOTE11PROKOROLOS.jpg",
    "fechaCompra":"2022-02-01",
    "precio":"20985000",
    "usuario":{"_id":"6485347d8d20455aa0a60537"},
    "marca":{"_id":"64852d59dea3acbaf550f055"},
    "tipoEquipo":{"_id":"64852daddea3acbaf550f05c"},
    "estadoEquipo":{"_id":"64852d94dea3acbaf550f057"}
}


###Leer todos los datos
GET http://localhost:9000/api/inventario HTTP/1.2
Authorization: Bearer 

###Leer datos por ID
GET http://localhost:9000/api/inventario/64852d9fdea3acbaf550f05a HTTP/1.1
Authorization: Bearer 


###Actualizar
PUT http://localhost:9000/api/inventario/6402ca00d951a9e6295d552c HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "serial":"1020",
    "modelo":"Portátil Hp ",
    "descripción":"Portátil Hp 15 Ck2101la ",
    "color":"Negro",
    "foto":"https://exitocol.vtexassets.com/arquivos/ids/12683729/portatil-hp-14-ck2101la-celeron-4gb-1tera-negro-sin-sistema-operativo.jpg?v=637872094558300000",
    "fechaCompra":"2022-01-01",
    "precio":"20860000",
    "usuario":{"_id":"64027ea3fecccc2c152afa25"},
    "marca":{"_id":"6402bfd01b299330bc55e34d"},
    "tipoEquipo":{"_id":"6402926d7fe348d9e30c7e72"},
    "estadoEquipo":{"_id":"6402b8be893a84525c1caa02"}
}

###Eliminar
DELETE  http://localhost:9000/api/inventario/6402ca00d951a9e6295d552c HTTP/1.1
Authorization: Bearer 

